name: CI/CD Pipeline - React + Docker + SonarQube + Nexus

on:
  push:
    branches:
      - main

jobs:
  build-sonar-nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Start React App (Optional for Testing Purposes)
        run: npm run start &
      
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and Push Docker Image to Nexus
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.NEXUS_URL }}/react-docker-app:latest
