name: CI/CD Pipeline - React + Docker + SonarQube + Nexus + CentOS 9

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar-nexus-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust if needed

      - name: Install Dependencies
        run: npm install

      - name: Skip Tests for Now
        run: echo "Skipping tests temporarily for CI/CD setup"

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and Push Docker Image to Nexus
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.NEXUS_URL }}/react-docker-app:latest

      - name: Deploy to CentOS 9 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Logging into Nexus Docker Registry..."
            docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}

            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.NEXUS_URL }}/react-docker-app:latest

            echo "Stopping existing container..."
            docker rm -f react-app || true

            echo "Running new container..."
            docker run -d -p 80:80 --name react-app ${{ secrets.NEXUS_URL }}/react-docker-app:latest
